---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: impermanent
spec:
  volumeName: impermanent
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: impermanent
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-path
  hostPath:
    path: /tmp/media/
